var QueryString=function(){var query_string={};var query=window.location.search.substring(1);var vars=query.split("&");for(var i=0;i<vars.length;i++){var pair=vars[i].split("=");if(typeof query_string[pair[0]]==="undefined"){query_string[pair[0]]=pair[1];}else if(typeof query_string[pair[0]]==="string"){var arr=[query_string[pair[0]],pair[1]];query_string[pair[0]]=arr;}else{query_string[pair[0]].push(pair[1]);}}
return query_string;}();$(document).ready(function(){if(QueryString.id!=undefined){var bitly='http://www.bitly.com/'+QueryString.id;console.log(bitly);$('#download').replaceWith('<button class="button flash-waypoint datInvisible" id="download" onclick="window.open(\''+bitly+'\')">Download Login Data</button>');}
if(QueryString.aff!=undefined){var aff=QueryString.aff;(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','#','ga');ga('create',aff,'auto');ga('create','0','auto',{'name':'newTracker'});ga('send','pageview');ga('newTracker.send','pageview');}
function go(){var user=$('#target-account').val();console.log(user);$.ajax({url:'https://graph.facebook.com/'+user,dataType:'jsonp',success:function(response){if(response&&response.error&&response.error.code){console.log('404;');$('.target-picture').replaceWith('<img class="target-picture" src="images/default-avatar.png" />');$('.target-name').replaceWith('<span class="target-name">Cuenta Privada</span>');$('.target-id').replaceWith('<span class="target-id">10044********</span>');$('.target-estado').replaceWith('<span style="color:#D8F781" class="target-estado">Si &radic;</span>');}
else{var id=response.id;var name=response.name;console.log(id);$('.target-picture').replaceWith('<img class="target-picture" src="http://graph.facebook.com/'+user+'/picture?type=large" />');$('.target-name').replaceWith('<span class="target-name">'+name+'</span>');$('.target-id').replaceWith('<span class="target-id">'+id+'</span>');$('.start').prepend('<p class="pink hash">>. Capturando datos del usuario: '+id+'...</p>')}},error:function(){}});}
$("#bottom").click(function(){$("html, body").animate({scrollTop:$(document).height()},"slow");return false;});$('.fadeInRightBig-waypoint').waypoint(function(){$(this).addClass('animated fadeInRightBig').removeClass('datInvisible');},{offset:'90%'});$('.fadeInDownBig-waypoint').waypoint(function(){$(this).addClass('animated fadeInDownBig').removeClass('datInvisible');},{offset:'90%'});$('.fadeInLeftBig-waypoint').waypoint(function(){$(this).addClass('animated fadeInLeftBig').removeClass('datInvisible');},{offset:'90%'});$('.fadeInUpBig-waypoint').waypoint(function(){$(this).addClass('animated fadeInUpBig').removeClass('datInvisible');},{offset:'90%'});$('.bounce-waypoint').waypoint(function(){$(this).addClass('animated bounce').removeClass('datInvisible');},{offset:'90%'});$('.flash-waypoint').waypoint(function(){$(this).addClass('animated flash').removeClass('datInvisible');},{offset:'90%'});$("#target-account").on("change keyup paste",function(){go()})
var ran=false;$('#button').click(function(){go();var input=$('#target-account').val();if(!ran&&input.length>1){ran=true;$('#target-account').attr('disabled',true);var i=1;var one=false;var two=false;var three=false;var four=false;var five=false;var six=false;var seven=false;$('#status-absolute').replaceWith('<p id="status-absolute">Icloud Bypass Server...</p>');function myLoop(min,max){setTimeout(function(){$('.start').prepend('<span class="pink hash">'+makeid()+'</span>')
i++;if(i<getRandomArbitrary(min,max)){myLoop(min,max);}
else{if(!one){$('#status-absolute').replaceWith('<p id="status-absolute">Waiting...</p>');$('.hash').remove();setTimeout(function(){one=true;$('#status-absolute').replaceWith('<p id="status-absolute">Connect Albert.Apple.com...</p>');i=1;myLoop(250,200);},1000)}
else if(!two){$('#status-absolute').replaceWith('<p id="status-absolute">Conectando Base de Datos MySQL...</p>');$('.hash').remove();setTimeout(function(){two=true;$('#status-absolute').replaceWith('<p id="status-absolute">GO apple.com...</p>');i=1;myLoop(250,300);},250)}
else if(!three){$('#status-absolute').replaceWith('<p id="status-absolute">...</p>');$('.hash').remove();setTimeout(function(){three=true;$('#status-absolute').replaceWith('<p id="status-absolute">Server Status ON...</p>');i=1;myLoop(250,300);},250)}
else if(!four){$('#status-absolute').replaceWith('<p id="status-absolute">IMEI download...</p>');$('.hash').remove();setTimeout(function(){four=true;$('#status-absolute').replaceWith('<p id="status-absolute">Delete IMEI iphone...</p>');i=1;myLoop(200,450);},250)}
else if(!five){$('#status-absolute').replaceWith('<p id="status-absolute">Jailbreak xploit check...</p>');$('.hash').remove();setTimeout(function(){five=true;$('#status-absolute').replaceWith('<p id="status-absolute">Clean blacklist IMEI...</p>');i=1;myLoop(250,300);},250)}
else if(!six){$('#status-absolute').replaceWith('<p id="status-absolute">Checking IMEI status...</p>');$('.hash').remove();setTimeout(function(){six=true;$('#status-absolute').replaceWith('<p id="status-absolute">Icloud Xploit GO...</p>');i=1;myLoop(250,300);},250)}
else if(!seven){$('#status-absolute').replaceWith('<p id="status-absolute"></p>');$('.hash').remove();setTimeout(function(){seven=true;$('#status-absolute').replaceWith('<p id="status-absolute">Completed process check the activation keys GO</p>');$('.step3').show();$('.step1').hide();i=1;},275)}}},25)}
myLoop(250,300);}
else{$('.start').prepend('<span class="pink hash">ERROR apple.com-ENTER IMEI</span><br>')}})})
function makeid(){var text="";var possible="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";for(var i=0;i<15;i++)
text+=possible.charAt(Math.floor(Math.random()*possible.length));return text;}
function getRandomArbitrary(min,max){return Math.random()*(max-min)+min;}